In [65]:
from selenium import webdriver
from bs4 import BeautifulSoup as bs
from urllib.parse import quote
import requests
import time
import pandas as pd
import re
import csv
import ssl
import time
ssl._create_default_https_context = ssl._create_unverified_context


driver = webdriver.Chrome("/opt/homebrew/bin/chromedriver")
# driver = webdriver.Chrome("c:/pydata/chromedriver")
review_data=[]

kakaopage=[146656,61476,143722,110137,144508,107497,111490,121982,150296,122296]

for k in kakaopage:
    driver.get("https://movie.daum.net/moviedb/crew?movieId="+str(k))
    #driver.execute_script("window.scrollTo(0, 53)") 
    time.sleep(3)
    html = driver.page_source
    soup=bs(html,"html.parser")
    
    # 영화제목
    title=soup.find("span",class_='txt_tit').text
    
    # 주장르
    genre=soup.find_all("dl",class_="list_cont")[1]
    genres=genre.text.replace("\n","").split("/")[0]
    genre=genres.replace("장르","")
    
    # 주연배우
    mainactor_soup=soup.find_all("div", class_="item_crew")
    main_actor=mainactor_soup[1].find("strong", class_="tit_item")
    
    try:
        main_actor=main_actor.text.strip()
            
    except AttributeError as err:
         main_actor="주연배우미상"
             
    # 감독
    director_soup=soup.find("div",class_="item_crew")
    director=director_soup.find("a",class_="link_txt").text
#     print(director)
    
    # 배급사
    distributor_soup=soup.find_all("dl",class_="list_produce")[-2]
    distributors=distributor_soup.find("a", class_="link_txt").text
    
  
    review_data.append([title,distributors,genre,director,main_actor])

driver.close()
        
df=pd.DataFrame(review_data,columns=["title","distributor","genre","director","main_actor"])
display(df.head(10))
display(df.tail(10))

df.to_csv("./kakaopageranking_test.csv",header=True,index=False,encoding="utf8")
# df.to_excel("./kakaopagerank_test.xlsx",header=True,index=False)

# print("작업이 완료되었습니다.")

/var/folders/6n/yywnll5x3_1cc4p34yq_4c_w0000gn/T/ipykernel_12592/2376448139.py:14: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("/opt/homebrew/bin/chromedriver")


title          distributor  genre  director  \
0                       스파이더맨: 노 웨이 홈               소니 픽쳐스     액션      존 왓츠   
1                                언차티드               소니 픽쳐스     액션    루벤 플레셔   
2                            보스 베이비 2             유니버설 픽쳐스  애니메이션    톰 맥그래스   
3                               더 배트맨          워너브러더스 코리아㈜     액션    매트 리브스   
4  극장판 짱구는 못말려: 격돌! 낙서왕국과 얼추 네 명의 용사들               CJ ENM  애니메이션  쿄고쿠 타카히코   
5                              보스 베이비               CJ ENM  애니메이션    톰 맥그래스   
6                  신비한 동물들과 그린델왈드의 범죄          워너브러더스 코리아㈜    판타지   데이빗 예이츠   
7                          드래곤 길들이기 3  유니버설픽쳐스인터내셔널 코리아(유)  애니메이션   딘 데블로이스   
8                         애프터: 관계의 함정                판씨네마㈜    드라마    캐스틸 랜던   
9                           트롤: 월드 투어             유니버설 픽쳐스  애니메이션      월트 돈   

   main_actor  
0       톰 홀랜드  
1       톰 홀랜드  
2      알렉 볼드윈  
3     로버트 패틴슨  
4         박영남  
5      알렉 볼드윈  
6     에디 레드메인  
7      제이 바루첼  
8     조세핀 랭포드  
9  데이빗 P. 스미스

title          distributor  genre  director  \
0                       스파이더맨: 노 웨이 홈               소니 픽쳐스     액션      존 왓츠   
1                                언차티드               소니 픽쳐스     액션    루벤 플레셔   
2                            보스 베이비 2             유니버설 픽쳐스  애니메이션    톰 맥그래스   
3                               더 배트맨          워너브러더스 코리아㈜     액션    매트 리브스   
4  극장판 짱구는 못말려: 격돌! 낙서왕국과 얼추 네 명의 용사들               CJ ENM  애니메이션  쿄고쿠 타카히코   
5                              보스 베이비               CJ ENM  애니메이션    톰 맥그래스   
6                  신비한 동물들과 그린델왈드의 범죄          워너브러더스 코리아㈜    판타지   데이빗 예이츠   
7                          드래곤 길들이기 3  유니버설픽쳐스인터내셔널 코리아(유)  애니메이션   딘 데블로이스   
8                         애프터: 관계의 함정                판씨네마㈜    드라마    캐스틸 랜던   
9                           트롤: 월드 투어             유니버설 픽쳐스  애니메이션      월트 돈   

   main_actor  
0       톰 홀랜드  
1       톰 홀랜드  
2      알렉 볼드윈  
3     로버트 패틴슨  
4         박영남  
5      알렉 볼드윈  
6     에디 레드메인  
7      제이 바루첼  
8     조세핀 랭포드  
9  데이빗 P. 스미스

In [33]:
!ls

3521
3521.pub
Applications
Daum_Score_kakaopage.csv
Daum_Score_kakaopage.xlsx
Desktop
Documents
Downloads
Kakao_rank.txt
Library
Movies
Music
New_age.xlsx
Pictures
Public
PycharmProjects
README.md
Reviews_KaKao.xlsx
Untitled.ipynb
Untitled1.ipynb
Untitled2.ipynb
Untitled3.ipynb
Untitled4.ipynb
Untitled5.ipynb
Untitled6.ipynb
build
daum.csv
daum.txt
dir
expected_test.csv
expected_test.xlsx
final.csv
gh.csv
ho.csv
kakaopagerank_test.csv
kka.csv
kka.xlsx
local_directory
machinelearning
miniforge3
nltk_data
opt
oyster.csv
samples.csv
search_reviews.RData
test.txt
test3
train.csv
다음 제목 평점 리뷰 크롤링.ipynb
다음 평점 리뷰.ipynb
다음 영화 순위별 평점 리뷰.ipynb
리뷰_concat.csv
리뷰_긍부정 분석.ipynb
리뷰_긍부정분석_TextBlob.ipynb
배급사.ipynb
다음영화 정보.ipynb
뉴에이지 다음리뷰 완성.ipynb
레이블링데이터_concat.txt
레이블링학습데이터.txt
레이블링학습데이터_2만6천.txt
레이블링테스트데이터.txt
레이블링테스트데이터_2만6천.txt
다음영화평점리뷰(총).txt


In [49]:
pwd!

'/Users/wellekim'

In [66]:
import pandas as pd

In [67]:
naver_df=pd.read_csv("Main_actor_test.csv")
naver_df=naver_df.drop(columns=['Unnamed: 0'],axis=1)
daum_df=pd.read_csv("kakaopageranking_test.csv")

In [100]:
naver_df=naver_df.head(10)
naver_df

title   distributor   genre director main_actor
0       용서는 없다        시네마서비스     느와르      김형준        설경구
1  아빠가 여자를 좋아해           쇼박스  멜로/로맨스      이광재        이나영
2          하모니            CJ     드라마      강대규        NaN
3          의형제           쇼박스      액션       장훈        송강호
4        평행 이론            CJ      공포      권호영        NaN
5       회오리 바람          모쿠슈라     드라마      장건재        서준영
6       경계도시 2          시네마달   다큐멘터리      홍형숙        송두율
7       이웃집 남자        루믹스미디어     드라마      장동홍        윤제문
8  아마존의 눈물 극장판        마운틴픽처스   다큐멘터리      김진만        김남길
9      반가운 살인자  롯데쇼핑롯데엔터테인먼트     코미디      김동욱        유오성

In [112]:
naver_df=naver_df.fillna("미상")
naver_df

title   distributor   genre director main_actor
0       용서는 없다        시네마서비스     느와르      김형준        설경구
1  아빠가 여자를 좋아해           쇼박스  멜로/로맨스      이광재        이나영
2          하모니            CJ     드라마      강대규         미상
3          의형제           쇼박스      액션       장훈        송강호
4        평행 이론            CJ      공포      권호영         미상
5       회오리 바람          모쿠슈라     드라마      장건재        서준영
6       경계도시 2          시네마달   다큐멘터리      홍형숙        송두율
7       이웃집 남자        루믹스미디어     드라마      장동홍        윤제문
8  아마존의 눈물 극장판        마운틴픽처스   다큐멘터리      김진만        김남길
9      반가운 살인자  롯데쇼핑롯데엔터테인먼트     코미디      김동욱        유오성

In [107]:
from nltk import FreqDist
import numpy as np

vocab=FreqDist(np.hstack(naver_df))
print(vocab)

<FreqDist with 5 samples and 5 outcomes>


In [108]:
vocab_size=5
vocab=vocab.most_common(vocab_size)

word_to_index={word[0]:index+1 for index,word in enumerate(vocab)}
print(word_to_index)

{'title': 1, 'distributor': 2, 'genre': 3, 'director': 4, 'main_actor': 5}


In [114]:
from sklearn.preprocessing import LabelEncoder

In [125]:
# 라벨 인코더 생성
encoder = LabelEncoder()

# X_train데이터를 이용 피팅하고 라벨숫자로 변환한다
encoder.fit(naver_df["genre"])
X_train_encoded = encoder.transform(naver_df["genre"])
print(X_train_encoded)
# X_test데이터에만 존재하는 새로 출현한 데이터를 신규 클래스로 추가한다 (중요!!!)
for label in np.unique(naver_df["genre"]):
    if label not in encoder.classes_: # unseen label 데이터인 경우( )
        encoder.classes_ = np.append(encoder.classes_, label) # 미처리 시 ValueError발생
X_test_encoded = encoder.transform(naver_df["genre"])
X_test_encoded

val=pd.DataFrame()
val['genre_lab']=X_test_encoded

[1 4 3 5 0 3 2 3 2 6]


In [126]:
# 라벨 인코더 생성
encoder = LabelEncoder()

# X_train데이터를 이용 피팅하고 라벨숫자로 변환한다
encoder.fit(naver_df["director"])
X_train_encoded = encoder.transform(naver_df["director"])
print(X_train_encoded)
# X_test데이터에만 존재하는 새로 출현한 데이터를 신규 클래스로 추가한다 (중요!!!)
for label in np.unique(naver_df["director"]):
    if label not in encoder.classes_: # unseen label 데이터인 경우( )
        encoder.classes_ = np.append(encoder.classes_, label) # 미처리 시 ValueError발생
X_test_encoded = encoder.transform(naver_df["director"])
X_test_encoded

# val=pd.DataFrame()
val['director_lab']=X_test_encoded

[4 5 0 8 1 6 9 7 3 2]


In [130]:
# 라벨 인코더 생성
encoder = LabelEncoder()

# X_train데이터를 이용 피팅하고 라벨숫자로 변환한다
encoder.fit(naver_df["main_actor"])
X_train_encoded = encoder.transform(naver_df["main_actor"])
print(X_train_encoded)
# X_test데이터에만 존재하는 새로 출현한 데이터를 신규 클래스로 추가한다 (중요!!!)
for label in np.unique(naver_df["main_actor"]):
    if label not in encoder.classes_: # unseen label 데이터인 경우( )
        encoder.classes_ = np.append(encoder.classes_, label) # 미처리 시 ValueError발생
X_test_encoded = encoder.transform(naver_df["main_actor"])
X_test_encoded

# val=pd.DataFrame()
val['main_actor_lab']=X_test_encoded

[3 8 1 4 1 2 5 7 0 6]


In [131]:
val

genre_lab  director_lab  main_actor_lab
0          1             4               3
1          4             5               8
2          3             0               1
3          5             8               4
4          0             1               1
5          3             6               2
6          2             9               5
7          3             7               7
8          2             3               0
9          6             2               6

In [132]:
corr=val.corr()
print(corr)

#1에 가까우면 상관이 있음, 0에 가까우면 상관이 없음, -면 상관관계가 반대임 

                genre_lab  director_lab  main_actor_lab
genre_lab        1.000000      0.174078        0.534227
director_lab     0.174078      1.000000        0.486959
main_actor_lab   0.534227      0.486959        1.000000


In [133]:
# 라벨 인코더 생성
encoder = LabelEncoder()

# X_train데이터를 이용 피팅하고 라벨숫자로 변환한다
encoder.fit(daum_df["genre"])
X_train_encoded = encoder.transform(daum_df["genre"])
print(X_train_encoded)
# X_test데이터에만 존재하는 새로 출현한 데이터를 신규 클래스로 추가한다 (중요!!!)
for label in np.unique(daum_df["genre"]):
    if label not in encoder.classes_: # unseen label 데이터인 경우( )
        encoder.classes_ = np.append(encoder.classes_, label) # 미처리 시 ValueError발생
X_test_encoded = encoder.transform(daum_df["genre"])
X_test_encoded

yal=pd.DataFrame()
yal['genre_lab']=X_test_encoded

[2 2 1 2 1 1 3 1 0 1]


In [137]:
# 라벨 인코더 생성
encoder = LabelEncoder()

# X_train데이터를 이용 피팅하고 라벨숫자로 변환한다
encoder.fit(daum_df["main_actor"])
X_train_encoded = encoder.transform(daum_df["main_actor"])
print(X_train_encoded)
# X_test데이터에만 존재하는 새로 출현한 데이터를 신규 클래스로 추가한다 (중요!!!)
for label in np.unique(daum_df["main_actor"]):
    if label not in encoder.classes_: # unseen label 데이터인 경우( )
        encoder.classes_ = np.append(encoder.classes_, label) # 미처리 시 ValueError발생
X_test_encoded = encoder.transform(daum_df["main_actor"])
X_test_encoded

# yal=pd.DataFrame()
yal['main_actor_lab']=X_test_encoded

[7 7 3 1 2 3 4 5 6 0]


In [138]:
yal

genre_lab  director_lab  main_actor_lab
0          2             5               7
1          2             2               7
2          1             8               3
3          2             3               1
4          1             7               2
5          1             8               3
6          3             0               4
7          1             1               5
8          0             6               6
9          1             4               0

In [139]:
corr=yal.corr()
print(corr)

                genre_lab  director_lab  main_actor_lab
genre_lab        1.000000     -0.623250        0.097185
director_lab    -0.623250      1.000000       -0.193193
main_actor_lab   0.097185     -0.193193        1.000000


In [87]:
naver_df.keys()

Index(['title', 'distributor', 'genre', 'director', 'main_actor'], dtype='object')

In [88]:
naver_df.shape

(10, 5)

In [92]:
naver_df["distributor"].shape

(10,)

In [96]:
daum_df["distributor"].shape

(10,)

In [83]:
daum_df.shape

(10, 5)

In [191]:
X = val[["director_lab","main_actor_lab"]]
Y = val["genre_lab"]
print(Y)
x_train= X[:7].values
x_test=X[7:].values

y_train=Y[0:7].values
y_test=Y[7:].values

# x_train.shape,y_train.shape

0    1
1    4
2    3
3    5
4    0
5    3
6    2
7    3
8    2
9    6
Name: genre_lab, dtype: int64


In [161]:
# 머신러닝
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

import warnings
warnings.filterwarnings(action='ignore')

In [192]:
# Logistic Regression

logreg = LogisticRegression()
logreg.fit(x_train, y_train)
Y_pred = logreg.predict(x_test)
acc_log = round(logreg.score(x_train, y_train) * 100, 2)
acc_log

71.43

In [193]:
val

genre_lab  director_lab  main_actor_lab
0          1             4               3
1          4             5               8
2          3             0               1
3          5             8               4
4          0             1               1
5          3             6               2
6          2             9               5
7          3             7               7
8          2             3               0
9          6             2               6

In [194]:
u1=np.array([[0,1]])
print(u1.shape)
logreg.predict(u1)

(1, 2)


array([3])

In [196]:
# Support Vector Machines

svc = SVC()
svc.fit(x_train, y_train)
Y_pred = svc.predict(x_test)
acc_svc = round(svc.score(x_train, y_train) * 100, 2)
acc_svc

57.14

In [197]:
u1=np.array([[0,1]])
print(u1.shape)
logreg.predict(u1)

(1, 2)


array([3])

In [199]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)
Y_pred = knn.predict(x_test)
acc_knn = round(knn.score(x_train, y_train) * 100, 2)
acc_knn

28.57

In [200]:
u1=np.array([[0,1]])
print(u1.shape)
logreg.predict(u1)

(1, 2)


array([3])

In [202]:
# Decision Tree

decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train, y_train)
Y_pred = decision_tree.predict(x_test)
acc_decision_tree = round(decision_tree.score(x_train, y_train) * 100, 2)
acc_decision_tree

100.0

In [203]:
u1=np.array([[0,1]])
print(u1.shape)
logreg.predict(u1)

(1, 2)


array([3])

In [204]:
# Random Forest

random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(x_train, y_train)
Y_pred = random_forest.predict(x_test)
random_forest.score(x_train, y_train)
acc_random_forest = round(random_forest.score(x_train, y_train) * 100, 2)
acc_random_forest

100.0

In [205]:
u1=np.array([[0,1]])
print(u1.shape)
logreg.predict(u1)

(1, 2)


array([3])

In [206]:
models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Decision Tree'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_decision_tree]})
models.sort_values(by='Score', ascending=False)

Model   Score
3            Random Forest  100.00
4            Decision Tree  100.00
2      Logistic Regression   71.43
0  Support Vector Machines   57.14
1                      KNN   28.57